//
// Generated file, do not edit! Created by nedtool 5.4 from stack/mac/packet/CsrRequest.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __CSRREQUEST_M_H
#define __CSRREQUEST_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0504
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>stack/mac/packet/CsrRequest.msg:17</tt> by nedtool.
 * <pre>
 * packet CsrRequest extends cPacket
 * {
 *     int cResel;
 *     int prioTx;
 *     int pRsvpTx;
 * }
 * </pre>
 */
class CsrRequest : public ::omnetpp::cPacket
{
  protected:
    int cResel;
    int prioTx;
    int pRsvpTx;

  private:
    void copy(const CsrRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CsrRequest&);

  public:
    CsrRequest(const char *name=nullptr, short kind=0);
    CsrRequest(const CsrRequest& other);
    virtual ~CsrRequest();
    CsrRequest& operator=(const CsrRequest& other);
    virtual CsrRequest *dup() const override {return new CsrRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getCResel() const;
    virtual void setCResel(int cResel);
    virtual int getPrioTx() const;
    virtual void setPrioTx(int prioTx);
    virtual int getPRsvpTx() const;
    virtual void setPRsvpTx(int pRsvpTx);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CsrRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CsrRequest& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CSRREQUEST_M_H
